-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 18:57:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlibanhang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlibanhang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlibanhang` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quanlibanhang` ;

-- -----------------------------------------------------
-- Table `quanlibanhang`.`nhacungcap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`nhacungcap` (
  `SUPPLIER_ID` INT NOT NULL,
  `SUPPLIER_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `SUPPLIER_ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  `SUPPLIER_PHONE_NUM` VARCHAR(45) NULL DEFAULT NULL,
  `SUPPLIER_EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`SUPPLIER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`donhangnhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`donhangnhap` (
  `IMPORT_ID` VARCHAR(16) NOT NULL,
  `ORDER_TIME_IMP` DATE NULL DEFAULT NULL,
  `DELIVERY_IMP` DATE NULL DEFAULT NULL,
  `TOTAL_COST_IMP` VARCHAR(45) NULL DEFAULT NULL,
  `SUPPLIER_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IMPORT_ID`),
  INDEX `SUPPLIER_ID_idx` (`SUPPLIER_ID` ASC) VISIBLE,
  CONSTRAINT `SUPPLIER_ID`
    FOREIGN KEY (`SUPPLIER_ID`)
    REFERENCES `quanlibanhang`.`nhacungcap` (`SUPPLIER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`chitietdonhangnhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`chitietdonhangnhap` (
  `IMPORTDETAIL_ID` INT NOT NULL,
  `PRODUCT_ID` VARCHAR(45) NULL DEFAULT NULL,
  `QUANTITY_IMP` VARCHAR(45) NULL DEFAULT NULL,
  `COST_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `IMPORT_ID` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`IMPORTDETAIL_ID`),
  INDEX `IMPORT_ID_idx` (`IMPORT_ID` ASC) VISIBLE,
  CONSTRAINT `IMPORT_ID`
    FOREIGN KEY (`IMPORT_ID`)
    REFERENCES `quanlibanhang`.`donhangnhap` (`IMPORT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`khachhang` (
  `CUSTOMER_ID` INT NOT NULL,
  `CUSTOMER_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTOMER_ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTOMER_PHONE_NUMBER` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTOMER_EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`donhangxuat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`donhangxuat` (
  `EXPORT_ID` INT NOT NULL,
  `DELIVERY_TIME_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `ORDER_TIME_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `TOTAL_PRICE_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `CUSTOMER_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`EXPORT_ID`),
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  CONSTRAINT `CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `quanlibanhang`.`khachhang` (`CUSTOMER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`chitietdonhangxuat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`chitietdonhangxuat` (
  `EXPORTDETAIL_ID` INT NOT NULL,
  `PRODUCT_ID` VARCHAR(45) NULL DEFAULT NULL,
  `QUANTITY_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `PRICE_EXP` VARCHAR(45) NULL DEFAULT NULL,
  `EXPORT_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`EXPORTDETAIL_ID`),
  INDEX `EXPORT_ID_idx` (`EXPORT_ID` ASC) VISIBLE,
  CONSTRAINT `EXPORT_ID`
    FOREIGN KEY (`EXPORT_ID`)
    REFERENCES `quanlibanhang`.`donhangxuat` (`EXPORT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`sanpham` (
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `PRODUCT_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  `PRODUCT_PRICE` VARCHAR(45) NULL DEFAULT NULL,
  `PRODUCT_IVENTORY` VARCHAR(45) NULL DEFAULT NULL,
  `PRODUCT_TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `LOCATION_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`chitietsanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`chitietsanpham` (
  `SUPPLIER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  PRIMARY KEY (`SUPPLIER_ID`, `PRODUCT_ID`),
  INDEX `PRODUCT_ID_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `chitietsanpham_ibfk_1`
    FOREIGN KEY (`SUPPLIER_ID`)
    REFERENCES `quanlibanhang`.`nhacungcap` (`SUPPLIER_ID`),
  CONSTRAINT `chitietsanpham_ibfk_2`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `quanlibanhang`.`sanpham` (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`nguoidung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`nguoidung` (
  `tendangnhap` VARCHAR(45) NOT NULL,
  `matkhau` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tendangnhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`nhacungcap_has_sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`nhacungcap_has_sanpham` (
  `SUPPLIER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  PRIMARY KEY (`SUPPLIER_ID`, `PRODUCT_ID`),
  INDEX `PRODUCT_ID` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `nhacungcap_has_sanpham_ibfk_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `quanlibanhang`.`sanpham` (`PRODUCT_ID`),
  CONSTRAINT `nhacungcap_has_sanpham_ibfk_2`
    FOREIGN KEY (`SUPPLIER_ID`)
    REFERENCES `quanlibanhang`.`nhacungcap` (`SUPPLIER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`sanpham_has_khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`sanpham_has_khachhang` (
  `PRODUCT_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`, `CUSTOMER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlibanhang`.`vitriluutru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlibanhang`.`vitriluutru` (
  `LOCATION_ID` INT NOT NULL,
  `LOCATION_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `LOCATION_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  `LOCATION_REPOSITORY` VARCHAR(45) NULL DEFAULT NULL,
  `LOCATION_STATUS` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`LOCATION_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
